<Project Sdk="Microsoft.NET.Sdk">

  <!-- Testa regra de domínio: entidade, value object, invariante. -->
  <ItemGroup>
    <ProjectReference Include="..\..\src\IdentityGateway.Domain\IdentityGateway.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Bogus" />
  </ItemGroup>

</Project>
