<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\IdentityGateway.Infrastructure\IdentityGateway.Infrastructure.csproj" />
    <ProjectReference Include="..\IdentityGateway.Application\IdentityGateway.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
